---
# ansible-playbook --vault-id rotating_passwords@prompt rotate_password.yml --vault-id password_salt@prompt -i inventory.yml --extra-vars "target=ansibledeploy" --ask-become-pass --ask-pass
- name: Bulk rotate user password from file
  hosts: '{{ target }}'
  become: true
  remote_user: ansible
  vars_prompt:
    - name: username
      prompt: 'Enter the user you want to change the password for'
      private: no
  vars_files:
    - variables/password_salt.yml
    - variables/new_passwords.yml
  tasks:
    - name: Check user exists on the remote host
      ansible.builtin.getent:
        database: passwd
        key: "{{ username }}"
    # - ansible.builtin.debug:
    #     var: ansible_facts.getent_passwd
    # - name: Debug what output would be
    #   debug:
    #     var: new_password
    - name: Change user password to supplied one
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ new_password }}"
        state: present